### ISSUE TITLE
提示位置缺乏灵活性

### ISSUE THREAD

**Issue by memotail** [why520crazy/angular-w5c-validator#11]
https://github.com/why520crazy/angular-w5c-validator/blob/master/src/w5cValidator.js#L41

有些情况，不是把错误插入到input的后面的，例如用bootstrap，有个视图是如：

	<div class="input-group">
		<div class="input-group-addon"><span class="glyphicon glyphicon-user"></span></div>
		<input name="name" type="text" class="form-control input-lg" placeholder="用户名/邮箱" ng-model="user.name" auto-focus="">
	</div>

那么，理论提示位置应该在input-group 后面，而不是input后面，否则样式被弄乱。

**Comment by aizigao** [comment]
可以这样
```html
<div class="input-group">
    <div class="input-group-addon"><span class="glyphicon glyphicon-user"></span></div>
    <input  type="text" class="form-control input-lg" placeholder="用户名/邮箱" ng-model="user.name" auto-focus="">
</div>


<input type='hidden' name='name' ng-model="user.name" required/>
```
两个model相同就可以，验证全放在 hidden那个input上
