### ISSUE TITLE
关于w5c-unique-check的问题

### ISSUE THREAD

**Issue by dusdong** [why520crazy/angular-w5c-validator#12]
1、即使配置为“光标移走不触发验证”，w5c-unique-check依然会在后台发送http指令去验证是否存在该值，只不过不显示验证结果而已。

2、w5c-unique-check 是否可以配置为使用函数验证？

3、我的代码w5c-unique-check已经返回true，但依然不提示错误，找了半天没发现问题。如果可以使用函数的话，或许调试会简单一些。

4、是否有手动添加错误信息的功能？比如，当我提交后，服务器会返回错误代码，我是否可以添加错误信息到 w5c-validator 中？

谢谢~

**Comment by why520crazy** [comment]
1. 因为唯一验证比较特殊，需要调用AJAX调用，所以光标移走会触发请求，当点击提交的时候会显示结果，如果不这样做就会导致AJAX还在请求的时候已经验证通过了;
2 和 3. 至于是否可以配置为函数验证，我觉得是可以的，下个版本考虑修改;
4. 现在是可以做到的，现在所有的错误信息都放在 form.$errors里面，你只要使用 form.$errors.unshift 或者 form.$errors.push 错误即可
