### ISSUE TITLE
当把 <input> 封装成 directive 使用时，报错

### ISSUE THREAD

**Issue by dusdong** [why520crazy/angular-w5c-validator#13]
错误信息为：Error: [$parse:syntax] Syntax Error: Token '{' is unexpected, expecting []] at column 15 of the expression [[validateForm.{{modelText}}.$viewValue,0]] starting at [{{modelText}}.$viewValue,0]].

源码地址：http://pan.baidu.com/s/1i35o3C5

谢谢~

**Comment by dusdong** [comment]
我又看了下，原因是我在 directive 中，input的name设置成了变量，导致错误。如下：<input name="{{modelText}}">。

请问可以解决吗？

**Comment by dusdong** [comment]
经过几天的调试，终于解决了，就是改为添加input属性的方式：
link: function (scope, elem, attrs, controller) {
                elem.attr('name', scope.modelText);
                $compile(elem)(scope);
            }

**Comment by dusdong** [comment]
呃，问题没有解决。因为 内层的 <input> directive总是先于 外层的 w5cvlidator 执行link，导致 w5c link的时候，找不到这些 <input> 控件。

**Comment by why520crazy** [comment]
不好意思，春节期间在老家，没有看到，目前这个组件不支持动态设置name属性的。我回头研究一下

**Comment by dusdong** [comment]
我试了很多次，主要问题在于内层的<input> directive总是先于外层w5cvlidator directive，设置优先级也不好使，不知为什么

**Comment by why520crazy** [comment]
ng 验证 是不支持name属性为表达式的，如果想要动态修改name的值可以参考  http://www.cnblogs.com/whitewolf/p/3560418.html 

代码如下：
```
 .directive("dyName", [
        function () {
            return {
                require: "ngModel",
                link: function (scope, elem, attrs, ngModelCtr) {
                    var name = scope.$eval(attrs.dyName);
                    ngModelCtr.$name = name;
                    elem.attr("name", name);
                    var formCtr = elem.controller('form') || {
                            $addControl: angular.noop
                        };
                    formCtr.$addControl(ngModelCtr);

                    scope.$on('$destroy', function () {
                        formCtr.$removeControl(ngModelCtr);
                    });

                }
            };
        }
    ])
```
