### ISSUE TITLE
<select muliple ...>  .type 应该是"select-multiple" 请更正下

### ISSUE THREAD

**Issue by naifen00** [why520crazy/angular-w5c-validator#17]
elemTypes = ['text', 'password', 'email', 'number', 'url', ['textarea'], ['select-multiple'], ['select-one']];

**Comment by why520crazy** [comment]
已经在2.3.9版本 修复，具体参见， https://github.com/why520crazy/angular-w5c-validator/blob/master/CHANGELOG.md
