### ISSUE TITLE
当表单里有button时，romoveError传递进来的的elem是上一个（prev）元素表单元素

### ISSUE THREAD

**Issue by David-CodingSerf** [why520crazy/angular-w5c-validator#21]
当表单里有button时，romoveError传递进来的的elem是上一个（prev）元素表单元素
所以在下一个表单元素发生变化 时，当前想要移除样式的元素才会删除error信息

**Comment by why520crazy** [comment]
当表单里有button时 是什么意思？希望给出代码

**Comment by David-CodingSerf** [comment]
比如:
<form>
  <button>刷新</button>
  <input />
  <input />
  <button type="submit">提交</button>
</form>

**Comment by why520crazy** [comment]
目前没有测试这些异常的情况，form 按照 bootstrap 的标准的 form 结构去写就不会有问题，回头测试一下你说的问题，你可以把你的form改造一下，还有就是 input 必须有 ng-model 和name，具体可以看示例
http://blog.ngnice.com/angular-w5c-validator/example/index.html

多谢反馈

**Comment by why520crazy** [comment]
如果你的form 结构和bootstrap的不一致，你可以在config中 设置 addError 和 romoveError 方法达到你的目的

**Comment by why520crazy** [comment]
最新版本已经修复
