### ISSUE TITLE
repeat password 验证出现undefined

### ISSUE THREAD

**Issue by cq-wangg** [why520crazy/angular-w5c-validator#24]
<div class="form-group row">
                <div class="col-md-3 col-md-3-mid"><label class="label_rig">密码：</label></div>
                <div class="col-md-5 col-md-pad"><input type="password" required="" ng-model="member.pass" name="password" class="form-control" required="" placeholder="密码" ng-minlength="4" ng-maxlength="12"/></div>
            </div>
            <div class="form-group row">
                <div class="col-md-3 col-md-3-mid"><label class="label_rig">确认密码：</label></div>
                <div class="col-md-5 col-md-pad"><input type="password" name="repeatPassword" w5c-repeat="password" class="form-control" ng-model="member.confirmPass" required="" placeholder="确认密码"/>
                </div>
            </div>

html代码如上，先输确认密码1234，再输密码1234，就会出现undefined

**Comment by why520crazy** [comment]
我使用你的html 没有问题啊，不知道你具体是怎么使用的，或者是版本不对，你使用最新版本试试，可以参考 http://blog.ngnice.com/angular-w5c-validator/example/index.html

**Comment by RandomOS** [comment]
当angular js使用1.3的版本时，然后按cg-wangg所述的步骤可以复现现标题所诉的错误。

**Comment by why520crazy** [comment]
因为 ng 1.3 版本做了一些变更导致了这个问题，http://stackoverflow.com/questions/25739986/what-is-the-purpose-of-the-new-built-in-parse-validation-key-in-angular-1-3

我已经修复了，你升级到2.4.8版本试试

**Comment by RandomOS** [comment]
nice，v2.4.8 已经修复这个问题。
