### ISSUE TITLE
Cannot read property '$parsers' of undefined

### ISSUE THREAD

**Issue by vicenteyu** [why520crazy/angular-w5c-validator#26]
w5cValidator.min.js:2:5607

“e.$parsers.push(function(a){return d.$setValidity("repeat",a===d.$viewValue),a})}}}])....”

**Comment by vicenteyu** [comment]
w5cValidator.js 第382行

    .directive("w5cRepeat", [function () {
        'use strict';
        return {
            require: "ngModel",
            link   : function (scope, elem, attrs, ctrl) {
                var otherInput = elem.inheritedData("$formController")[attrs.w5cRepeat];

                ctrl.$parsers.push(function (value) {
                    if (value === otherInput.$viewValue) {
                        ctrl.$setValidity("repeat", true);
                        return value;
                    }
                    ctrl.$setValidity("repeat", false);
                });

                otherInput.$parsers.push(function (value) {
                    ctrl.$setValidity("repeat", value === ctrl.$viewValue);
                    return value;
                });
            }
        };
    }])

**Comment by why520crazy** [comment]
你在使用这个指令的时候必须有 ng-model

**Comment by vicenteyu** [comment]
噢，这样，习惯性加了data-ng-model，去掉之后无问题。建议加入判断提示。

**Comment by why520crazy** [comment]
OK 多谢反馈
