### ISSUE TITLE
页面加载完成后可以不让w5c validator立即校验吗？或者由我决定页面加载完成后要不要立即校验

### ISSUE THREAD

**Issue by liangzai-cool** [why520crazy/angular-w5c-validator#28]
页面加载完成后，不作任何操作：
引入：angular-w5c-validator/dist/w5cValidator.js：
![qq 20150722201113](https://cloud.githubusercontent.com/assets/6807169/8825012/fbd0bffe-30ad-11e5-8e45-6d8ce228e79b.png)

未引入angular-w5c-validator/dist/w5cValidator.js：
![qq 20150722201319](https://cloud.githubusercontent.com/assets/6807169/8825107/09025d76-30af-11e5-9de8-c03cc860b138.png)

另外，w5cValidator虽然使用的是基于ng的校验规则，但能否做到angularjs校验完后不进行任何操作，而让我在showError里进行自定义显示错误。

多谢！

**Comment by why520crazy** [comment]
1. 目前页面加载完成后是没有做任何事情的，你说是引入w5cValidator.js的原因，我试图去掉w5cValidator.js的引用也是有：
![image](https://cloud.githubusercontent.com/assets/3959960/8841802/f6a40bc2-3124-11e5-8032-f53bdeb10c6c.png)
不知道你的angular.js版本是否也有区别，我特意去 https://docs.angularjs.org/guide/forms 去看了下，默认也是有初始化的class的，这个应该没有什么问题；

2. 至于你说的 ”angularjs校验完后不进行任何操作“，angularjs的校验实时的，只要输入值有变换就会校验，但是 w5cValidator 并不是根据 angularjs 的Form验证显示错误信息，默认是光标移走显示错误信息，你也可以改成点击 提交按钮后 显示错误信息提示，当然 showError 和 removeError也是可以自定义的。

具体使用参考：http://blog.ngnice.com/angular-w5c-validator/example/index.html

希望能满足你的需求，有什么问题可以随时提出

**Comment by liangzai-cool** [comment]
#### 1、
看到你使用的应该是Chrome，我做了一个单独页面`angular_w5c_validator.html`，用FireFox和Chrome分别重现这个问题，html文件内容如下：
```html
<!DOCTYPE html>
<html ng-app>
	<head>
		<meta charset="utf-8">
		<title>title</title>
		<link href="angular-w5c-validator/src/style.css" />
	</head>
	<body>
	  
	  <form action="" name="validateForm" data-w5c-form-validate>
	    <input type="text" required="required" name="username" ng-model="user.username" ng-maxlength="20" ng-minlength="6" />
	  </form>
	  
	  <script src="angular-1.4.2/angular.js"></script>
	  <script src="angular-w5c-validator/dist/w5cValidator.js"></script>
	</body>
</html>
```
在FireFox 39.0(国际版)中效果：
![在FireFox 39.0(国际版)中效果](https://cloud.githubusercontent.com/assets/6807169/8850483/03f63088-317b-11e5-857e-a563dbdbce2d.png)
在Chrome 41中效果：
![在Chrome 41中效果](https://cloud.githubusercontent.com/assets/6807169/8850526/50f51aac-317b-11e5-8042-513509dd301b.png)

`name`为`username`的输入框类好像并没有发生什么变化，随后我修改了`angular_w5c_validator.html`，内容如下：
```html
<!DOCTYPE html>
<html ng-app="app">
	<head>
		<meta charset="utf-8">
		<title>title</title>
		<link href="angular-w5c-validator/src/style.css" />
	</head>
	<body>
	  
	  <form action="" name="validateForm" data-w5c-form-validate="">
	    <input type="text" required="required" name="username" ng-model="user.username" ng-maxlength="20" ng-minlength="6" />
	  </form>
	  
	  <script src="angular-1.4.2/angular.js"></script>
	  <script src="angular-w5c-validator/dist/w5cValidator.js"></script>
	  <script>
      (function() {
        var app = angular.module("app", ["w5c.validator"]);
      })();
	  </script>
	</body>
</html>
```
在FireFox 39.0(国际版)中效果：
![在FireFox 39.0(国际版)中效果](https://cloud.githubusercontent.com/assets/6807169/8850713/dc22ac06-317c-11e5-95dc-bb25aaa15484.png)
在Chrome 41中效果：
![在Chrome 41中效果](https://cloud.githubusercontent.com/assets/6807169/8850724/eb715fe0-317c-11e5-88ca-4562d4d8931c.png)

这次可以看到，相对于Chrome，FireFox中输入框多了一个`valid`类，我追踪到是在`dist/w5cValidator.js`，有下面这样一段代码，其中的`addClass`("valid")的结果。
```javascript
            removeError     : function (elem, options) {
                var useOptions = angular.extend({}, this.options, options);
                angular.element(elem).removeClass("error").addClass("valid");
                if (useOptions.removeError === false) {
                    return;
                }
                if (angular.isFunction(useOptions.removeError)) {
                    return useOptions.removeError(elem);
                }
                if (useOptions.removeError === true) {
                    return this.defaultRemoveError(elem);
                }
            }
```
触发上述`removeError`方法的地方是在下面一段代码中的`$watch`函数：
```javascript
                        (function (elem, $elem) {
                            //formCtrl[elem.name].$viewChangeListeners.push(function () {
                            //    formCtrl.$errors = [];
                            //    w5cValidator.removeError($elem, options);
                            //});
                            var $viewValueName = formName + "." + elem.name + ".$viewValue";
                            //监控输入框的value值当有变化时移除错误信息
                            //可以修改成当输入框验证通过时才移除错误信息，只要监控$valid属性即可
                            scope.$watch($viewValueName, function () {
                                formCtrl.$errors = [];
                                w5cValidator.removeError($elem, options);
                            }, true);
                        })(elem, $elem);
```
我是做后端的，对前端不太擅长，特别是刚刚接触了angularjs，所以目前的解决方案仅仅是修改上面代码中的`$watch`的回调函数如下：
```javascript
                            scope.$watch($viewValueName, function (newValue, oldValue, scope) {
                                if (oldValue == undefined && newValue == undefined) {
                                  return;
                                }
                                formCtrl.$errors = [];
                                w5cValidator.removeError($elem, options);
                            }, true);
```

#### 2、
嗯，deom和文档我都有仔细看过，你也看到angular的校验会自动添加一些`ng-pristine`、 `ng-untouched`、 `ng-invalid`、 `ng-invalid-required`、 `ng-valid-minlength`、 ·ng-valid-maxlength`这样的类，我不清楚angular加这些类是不是有其他用处，还是仅仅是为了样式？如果仅仅为了样式，那w5cValidator 能拦截到angular添加这些类的动作，以便让我来决定要不要添加或者做其他操作吗？

多谢！

**Comment by liangzai-cool** [comment]
我上面**1**处看错了，第3张图和第4张图中，FireFox和Chrome中都有`valid`类，问题不像是浏览器兼容性，而是是否在angular中注册了ngApp，`$watch`回调函数执行之后添加了valid。不注册ngApp时，不会执行那个`$watch`的回调函数。

多谢！

**Comment by why520crazy** [comment]
class valid 的确是你的说的那样，我监控了 输入框的值，第一次也触发了监控事件，导致开始加载有了一个 valid 样式，目前 valid 样式是什么都没有做，只有error样式才会起作用，这个我回头会修复一下

关于  `ng-pristine、 ng-untouched、 ng-invalid、 ng-invalid-required、 ng-valid-minlength、 ·ng-valid-maxlength` 这些样式都是 ng 自己初始化的时候加入的，作用就是为了验证失败的样式，你可以使用这些样式做自己的错误提示，ng 官方示例就是采用的这种方式提示错误的。

我写这个组件的目的就是简化 提示信息的，不用写很多ng模板，让提示信息通过简单配置下就可以满足需要，关于如何捕获 ng 添加的样式，我觉得没有必要做，你可以看下 ng 源码，在ngModel 这个directive中也是通过 $watch 做的，这些样式中有个  ng-dirty  表示输入框是否已经输入过内容，真的要做的话就等于自己重写了 ng 的验证机制了

**Comment by liangzai-cool** [comment]
好的。
jquery.validation 是我在jQuery世界里用过最好用的表单校验插件，
angular-w5c-validator 是我在Angular世界中用过最好用的表单校验插件。
加油 @why520crazy ~~~，希望angular-w5c-validator越来越好~~~

**Comment by why520crazy** [comment]
多谢支持，也欢迎你提出宝贵意见，同时也非常欢迎你一起贡献代码
