### ISSUE TITLE
密码双向验证

### ISSUE THREAD

**Issue by chanzig** [why520crazy/angular-w5c-validator#29]
bootstrap的这个密码验证，只设置了确认密码验证新密码，而没有设置新密码去验证确认密码的机制。假如我给新密码也绑定一个和确认密码验证的参数方法。体验很不好的说。

反正目前我看到几乎用bootstrap做的网站登录的时候，几乎没有双向绑定的，当我输完确认密码，返回去改编新密码，不会触发确认密码框的再次校验，然后验证都是通过的，ok神奇的事情出现了，没有后台验证的直接提示注册成功了

**Comment by why520crazy** [comment]
你说的这个问题吧其实也很好解决，但是一般没有做这个功能的必要，现在很多网站都不会多一个 确认密码的输入框了，有确认密码输入框 只是验证下是否有输错的可能。在 http://blog.ngnice.com/angular-w5c-validator/example/index.html 示例中虽然你重新输入密码不会触发错误事件，但是你只要提交还是不会通过的
![image](https://cloud.githubusercontent.com/assets/3959960/8898169/bdc85fc0-3452-11e5-886f-6b6f65e15423.png)

**Comment by why520crazy** [comment]
现在这个问题可以通过自定义验证做到，升级到2.4.9版本后，在2个密码上上都绑定 
` w5c-customizer="vm.customizerPwdRepeat()"` 验证2个密码是否相同
