### ISSUE TITLE
TypeError: Cannot set property '$errors' of undefined

### ISSUE THREAD

**Issue by usergyt** [why520crazy/angular-w5c-validator#30]
TypeError: Cannot set property '$errors' of undefined
    at Object.fn (w5cValidator.min.js:2)
    at n.$get.n.$digest (angular.js:15685)
    at n.$get.n.$apply (angular.js:15953)
    at controller.doValidate (w5cValidator.min.js:2)
    at HTMLInputElement.<anonymous> (w5cValidator.min.js:2)
    at HTMLInputElement.c (angular.js:3273)

**Comment by why520crazy** [comment]
你是怎么使用的？

**Comment by usergyt** [comment]
就是在弹层上 hide的时候 报的异常

**Comment by usergyt** [comment]
scope[formName].$errors = [];  这行报的

**Comment by why520crazy** [comment]
你的form设置name属性了吗？

**Comment by usergyt** [comment]
设置了

**Comment by usergyt** [comment]
<form class="form-horizontal w5c-form demo-form clearfix" role="form"
     w5c-form-validate="vm.validateOptions" novalidate name="validateForm"  name="validateForm">
    <div class="form-group">

**Comment by why520crazy** [comment]
你使用的是最新版本吗？

**Comment by why520crazy** [comment]
能把完整的html贴出来吗？

**Comment by why520crazy** [comment]
和 示例代码有什么区别吗？http://blog.ngnice.com/angular-w5c-validator/example/index.html

**Comment by usergyt** [comment]
额 不是最新的 ，等我更新完了 在测下吧。谢谢

**Comment by why520crazy** [comment]
这个现在还有问题吗？
