### ISSUE TITLE
能不能忽略单个文本框校验

### ISSUE THREAD

**Issue by zxj963577494** [why520crazy/angular-w5c-validator#31]
文本框的数据是从遮罩层中获取的，然而使用该模块后，会显示的错误是Undefined的(没有报错，直接在界面上显示)，我想直接忽略对这个文本框的校验，自己做校验算了

加了name通过不校验，不加name也通不过校验，不加任何校验属性也通不过校验，求教

**Comment by why520crazy** [comment]
显示的错误是Undefined是因为你给这个文本框加了验证，然而错误消息没有指定吧，不知道具体代码，如果这个文本框不想验证，不要加  require type="email" 这些 ng自带的验证指令即可，如果还不行，贴出代码或者在线示例

**Comment by zxj963577494** [comment]
@why520crazy  thk，是我自己的问题

**Comment by why520crazy** [comment]
不客气
