### ISSUE TITLE
input 后面的help-block 会被删除

### ISSUE THREAD

**Issue by moxuanyuan** [why520crazy/angular-w5c-validator#32]
input 后面要带help-block进行提示，但用了 w5cValidator.js 第63行中的 $elem.next(".w5c-error").remove(); 会把所有input 后面的help-block 删除

原因是next() - Does not support selectors 

https://docs.angularjs.org/api/ng/function/angular.element

解决方法将第62、63、64 行改为
             var elemNext=$elem.next();
                if(elemNext.hasClass('w5c-error')){
                    angular.forEach(elemNext,function(e){
                        e=angular.element(e);
                        if(e.hasClass('w5c-error'))e.remove();
                    });
                }

**Comment by why520crazy** [comment]
最新版本已经修复
