### ISSUE TITLE
表单字段设置ng-if验证通过了，显示报错的信息无法移除

### ISSUE THREAD

**Issue by chenli1989** [why520crazy/angular-w5c-validator#35]
<div class="form-group">
        <label class="col-sm-2 control-label">邮箱</label>
        <div class="col-sm-10">
            <input type="email" name="email" ng-model="entity.email" required="" class="form-control"
                   placeholder="输入邮箱">
        </div>
    </div>
    <div class="form-group" ng-if="entity.email">
        <label class="col-sm-2 control-label">邮箱</label>
        <div class="col-sm-10">
            <input type="email" name="email2" ng-model="entity.email2" required="" class="form-control"
                   placeholder="输入邮箱">
        </div>
    </div>

**Comment by why520crazy** [comment]
目前不支持表单内有动态元素，比如说 ng-if ，回头看看怎么可以支持

**Comment by chenli1989** [comment]
表单里有切换视图时，就无法实现了，尝试了下ng-show，在不显示时，也执行验证。可有其它处理方案？

**Comment by why520crazy** [comment]
暂时应该没有其他方案处理这种需求，可以修改源代码，让其支持忽略某个元素的验证

**Comment by chenli1989** [comment]
尝试了修改源代码，在初始化时，监听form里有动态元素的变量，再实例化表单字段验证。暂时可以解决问题，我把修改的代码贴上来。您看下有没问题：
//初始化验证规则，并时时监控输入值的变话
                    var doEach = function() {
                        for (var i = 0; i < formElem.length; i++) {
                            var elem = formElem[i];
                            var $elem = angular.element(elem);
                            if (w5cValidator.elemTypes.toString().indexOf(elem.type) > -1 && !w5cValidator.isEmpty(elem.name)) {
                                (function(elem, $elem) {
                                    //formCtrl[elem.name].$viewChangeListeners.push(function () {
                                    //    formCtrl.$errors = [];
                                    //    w5cValidator.removeError($elem, options);
                                    //});
                                    var $viewValueName = formName + "." + elem.name + ".$viewValue";
                                    //监控输入框的value值当有变化时移除错误信息
                                    //可以修改成当输入框验证通过时才移除错误信息，只要监控$valid属性即可
                                    scope.$watch($viewValueName, function() {
                                        formCtrl.$errors = [];
                                        w5cValidator.removeError($elem, options);
                                    }, true);
                                })(elem, $elem);


                                //光标移走的时候触发验证信息
                                if (options.blurTrig) {
                                    $elem.bind("blur", function() {
                                        if (!options.blurTrig) {
                                            return;
                                        }
                                        var self = this;
                                        var $elem = angular.element(self);
                                        $timeout(function($elem) {
                                            $elem = $elem || angular.element(self);
                                            if (!formCtrl[self.name].$valid) {
                                                var errorMessages = w5cValidator.getErrorMessages(self, formCtrl[self.name].$error);
                                                w5cValidator.showError($elem, errorMessages, options);
                                            } else {
                                                w5cValidator.removeError($elem, options);
                                            }
                                        }, 50);
                                    });
                                }
                            }
                        }
                    }
                    doEach();
                    scope.$watch(attr.formChange, function(newValue, oldValue, scope) {
                        if (!angular.equals(newValue, oldValue)) {
                            doEach();
                        }
                    }, true);
attr.formChange 是监听的动态变量，这个处理有个小问题出现，在原本有报错显示的情况下，监听的动态变量时，会把之前报错状态给移除了。

**Comment by why520crazy** [comment]
你好，升级到2.4.0版本就可以支持动态Form验证了，目前应该能配合ng-if使用，需要在ng-if 内部的input上加w5c-dynamic-element指令, 使用方法参考 http://why520crazy.github.io/angular-w5c-validator
