### ISSUE TITLE
如何自定义验证的消息

### ISSUE THREAD

**Issue by HuDonie** [why520crazy/angular-w5c-validator#41]
如何自定义验证的消息，如下能不能在界面上定义一个属性，填写错误消息，没有errMessage这个属性的就按默认消息显示
              <input class="form-control" type="text" name="appName" ng-model="obj.appName"  ng-pattern="/^[A-Za-z]{1}[0-9A-Za-z_]{1,19}$/" errMessage="应用名称格式不正确，格式如：xxx-xx-xxx" id="appName">

**Comment by why520crazy** [comment]
目前只有在js配置中写 错误消息，在模板中写错误消息暂时不支持，以后可以考虑

**Comment by why520crazy** [comment]
你好，2.4.9版本中已经添加了自定义验证，你可以试试，
直接使用
```html
 <input type="text" w5c-customizer="vm.customizer()" ng-model="vm.entity.customizer" name="customizer" class="form-control"
                   placeholder="必须输入 why520crazy">

或者 

 <input type="text" w5c-customizer="vm.entity.customizer === 'why520crazy'" ng-model="vm.entity.customizer" name="customizer" class="form-control"
                   placeholder="必须输入 why520crazy">
```
参考demo：
 http://blog.ngnice.com/angular-w5c-validator/example/

**Comment by HuDonie** [comment]
customizer    : {
                customizer: "自定义验证数字必须大于上面的数字"
            }，这提示消息能不能在界面写呢？

如下代码显示的是errMessage

 <input type="text" w5c-customizer="vm.customizer()" ng-model="vm.entity.customizer" name="customizer" class="form-control"
                   placeholder="必须输入 why520crazy"  errMessage="自定义验证数字必须大于上面的数字">

**Comment by HuDonie** [comment]
又或者可不可以在controller上定义这个message,$scop.customizer= "自定义验证数字必须大于上面的数字",全局配置会影响所有的，有时候我们往往需要影响局部的

**Comment by why520crazy** [comment]
需要支持在模板上写错误消息，估计要写很多，因为一个元素会有多个验证，以后会考虑的

**Comment by HuDonie** [comment]
只需支持自义那种验证可以在模板上写错误消息，因为自定验证就是特殊的，所以消息不应该在全局的
