### ISSUE TITLE
如何定义验证提示信息

### ISSUE THREAD

**Issue by hudoro** [why520crazy/angular-w5c-validator#43]
自义那种验证错误消息不应该在全局配置的，因为自定验证就是特殊的，所以消息不应该在全局的

customizer : {
customizer: "自定义验证数字必须大于上面的数字"
}
这提示消息能不能在界面写呢，全局配置会影响所有的，有时候我们往往需要影响局部的？
如下代码显示的是errMessage

```
  <input type="text" w5c-customizer="vm.customizer()" ng-model="vm.entity.customizer" 
 name="customizer" class="form-control" placeholder="必须输入 why520crazy"
 errMessage="自定义验证数字必须大于上面的数字">
```

又或者可不可以在controller上定义这个message,$scop.customizer= "自定义验证数字必须大于上面的数字",全局配置会影响所有的，有时候我们往往需要影响局部的

如下又如何实现呢？

```
    vm.customizer = function () {
        if(vm.entity.customizer > vm.entity.number){
        customizer: "自定义验证数字必须大于上面的数字"
        }
       return false;
    };
```

**Comment by qq645381995** [comment]
我也是再看自定义的 可是好像只有config配置

**Comment by why520crazy** [comment]
自定义验证消息并不是全局的，提供的只是默认显示的名称而已，具体看：https://github.com/why520crazy/angular-w5c-validator/issues/44

**Comment by qq645381995** [comment]
看下 56 问题，如果name 是 length  错误信息不显示，
