### ISSUE TITLE
求助自定义验证在controller下赋值提示消息

### ISSUE THREAD

**Issue by HuDonie** [why520crazy/angular-w5c-validator#44]
求助自定义验证在controller下提示消息，因为全局验证我们在平台的，所以子项目不可能修改的，怎么办？
在controller上定义这个message,$scop.customizer= "自定义验证数字必须大于上面的数字"

如下又如何实现呢？

    vm.customizer = function () {
        if(vm.entity.customizer > vm.entity.number){
        customizer: "自定义验证数字必须大于上面的数字"
        }
       return false;
    };

**Comment by why520crazy** [comment]
你给每个子项目取一个不同的name即可

**Comment by HuDonie** [comment]
就是怎么样呢？
下面这个配置是在平台项目配置的，我们子项目不可以修改的，所以那个提示消息不知道怎么搞

         app.config(["w5cValidatorProvider", function (w5cValidatorProvider) {
					   // 全局配置
					    w5cValidatorProvider.config({
						blurTrig   : false,
						showError  : true,
						removeError: true

					 });
					  w5cValidatorProvider.setRules({
					   customizer    : {
							customizer: "自定义验证数字必须大于上面的数字"
						}
					});
				}]);

**Comment by why520crazy** [comment]
```js
w5cValidatorProvider.setRules({
                   form1Customizer    : {
                        customizer: "自定义验证数字必须大于上面的数字"
                    },
                  form2Customizer    : {
                        customizer: "自定义验证数字必须大于上面的数字"
                    }
                });
```

```html
<input w5c-customizer="xxxx" name="form1Customizer" />
<input w5c-customizer="xxxx" name="form2Customizer" />
```

**Comment by HuDonie** [comment]
Thank you for why520crazy  support,在子模块加这个配置就好了


				var exampleSysDocControllers = angular.module(namespace+'.controllers', []).config(["w5cValidatorProvider", function (w5cValidatorProvider) {
						w5cValidatorProvider.setRules({
							form1Customizer:{
								customizer: "自定义验证数字必须大于上面的数字xxxx"
							}
						});
					}]);
