### ISSUE TITLE
更新了最新w5c-validator的JS出现错误了

### ISSUE THREAD

**Issue by HuDonie** [why520crazy/angular-w5c-validator#45]
Error: [$parse:syntax] Syntax Error: Token '.15.' is an unexpected token at column 13 of the expression [validateForm.15.$viewValue] starting at [.15.$viewValue].
http://errors.angularjs.org/1.4.8/$parse/syntax?p0=.15.&p1=is%20an%20unexpected%20token&p2=13&p3=validateForm.15.%24viewValue&p4=.15.%24viewValue
    at http://localhost:8080/iportal/static/lib/plugins/angular-1.4.8/angular.js:68:12
    at Object.AST.throwError (http://localhost:8080/iportal/static/lib/plugins/angular-1.4.8/angular.js:13100:11)
    at Object.AST.ast (http://localhost:8080/iportal/static/lib/plugins/angular-1.4.8/angular.js:12870:12)
    at Object.ASTCompiler.compile (http://localhost:8080/iportal/static/lib/plugins/angular-1.4.8/angular.js:13319:31)
    at Parser.parse (http://localhost:8080/iportal/static/lib/plugins/angular-1.4.8/angular.js:14189:29)
    at $parse (http://localhost:8080/iportal/static/lib/plugins/angular-1.4.8/angular.js:14291:39)
    at Scope.$watch (http://localhost:8080/iportal/static/lib/plugins/angular-1.4.8/angular.js:15482:19)
    at initElement (http://localhost:8080/iportal/static/lib/plugins/angular-w5c-validator/w5cValidator.js:249:36)
    at link (http://localhost:8080/iportal/static/lib/plugins/angular-w5c-validator/w5cValidator.js:296:30)
    at invokeLinkFn (http://localhost:8080/iportal/static/lib/plugins/angular-1.4.8/angular.js:8841:9) <form class="form-horizontal w5c-form demo-form ng-pristine ng-valid" role="form" w5c-form-validate="validateOptions" novalidate="" name="validateForm">

**Comment by HuDonie** [comment]
把249行下面的代码注释掉就没问题，但是注释后提示还显示在那里， 这怎么解决了？

        $scope.$watch($viewValueName, function () {
                                ctrl.form.$errors = [];
                                w5cValidator.removeError($elem, ctrl.options);
                            }, true);

**Comment by HuDonie** [comment]
好奇怪的，就是弹出框里的表单才有问题，不是弹出框就没问题，什么原因呢

**Comment by why520crazy** [comment]
你把弹出框表单的代码贴出来看看，还有就是你的弹出窗是怎么做的

**Comment by why520crazy** [comment]
是不是你的元素的name是以数字为开头的？？

**Comment by HuDonie** [comment]
<div class="modal-dialog">
					<div class="modal-content">
						<div class="modal-header">
							<button type="button" class="close ngdialog-custom-close" data-dismiss="modal" aria-label="Close"><span class="ngdialog-custom-close" aria-hidden="true">&times;</span></button>
							<h4 class="modal-title">新增doc</h4>
						</div>
						<form class="form-horizontal w5c-form demo-form" role="form" w5c-form-validate="validateOptions" novalidate name="validateForm">
							<div class="modal-body">

								<div class="form-group">
									<label class="control-label col-md-3" for="title"><span style='color:red'>*</span>&nbsp;标题：</label>
									<div class="col-md-6">
										<input class="form-control" type="text" name="title" ng-model="obj.title" required ng-minlength="1" ng-maxlength="128" id="title">
									</div>
								</div>
								<div class="form-group">
									<label class="control-label col-md-3" for="summary"><span style='color:red'>*</span>&nbsp;摘要：</label>
									<div class="col-md-6">
										<input class="form-control" type="text" name="summary" ng-model="obj.summary" required ng-minlength="1" ng-maxlength="512"  id="summary">
									</div>
								</div>
								<div class="form-group">
									<label class="control-label col-md-3" for="link"><span style='color:red'>*</span>&nbsp;外连：</label>
									<div class="col-md-6">
										<input class="form-control" type="text" name="link" ng-model="obj.link" required  ng-minlength="1" ng-maxlength="128" id="link">
									</div>
								</div>
								<div class="form-group">
									<label class="control-label col-md-3" for="releaseVersion"><span style='color:red'>*</span>&nbsp;版本：</label>
									<div class="col-md-6">
										<input class="form-control" type="text" name="releaseVersion" ng-model="obj.releaseVersion" required  ng-minlength="1" ng-maxlength="32" id="releaseVersion">
									</div>
								</div>
								<div class="form-group">
									<label class="control-label col-md-3" for="cont"><span style='color:red'>*</span>&nbsp;内容：</label>
									<div class="col-md-6">
										<input class="form-control" type="text" name="cont" ng-model="obj.cont" required ng-minlength="1" ng-maxlength="2147483647" id="cont">
									</div>
								</div>
								<div class="form-group">
									<label class="control-label col-md-3" for="orderby"><span style='color:red'>*</span>&nbsp;顺序(数字)：</label>
									<div class="col-md-6">
										<input class="form-control" type="text" name="orderby" onkeyup="if(/\D/.test(value))value=value.replace(/\D/g,'')" ng-model="obj.orderby" required ng-minlength="1" ng-maxlength="100" id="orderby">
									</div>
								</div>
								<div class="form-group">
									<label class="control-label col-md-3"><span style='color:red'>*</span>&nbsp;是否可用：</label>
									<div class="col-md-9">
										<label class="radio-inline">
											<input type="radio" ng-model="obj.isAvailable"  value="Y"  ng-checked="true"> 可用
										</label>
										<label class="radio-inline">
											<input type="radio" ng-model="obj.isAvailable"  value="N"> 不可用
										</label>
									</div>
								</div>

							</div>
							<div class="modal-footer">
								<button type="buttom" w5c-form-submit="submit()" class="btn btn-success"> 保存</button>
								<button type="button" class="btn btn-default ngdialog-custom-close" data-dismiss="modal">关闭</button>
							</div>
						</form>
					</div>
				</div>

**Comment by HuDonie** [comment]
w5cValidator v2.4.3 是没问题的，w5cValidator v2.4.9才出现这个问题的

**Comment by HuDonie** [comment]
弹出框是用ngDialog做的http://ngmodules.org/modules/ngDialog，

       $scope.showAddWin = function showAddWin() {
                   $scope.addWin = ngDialog.open({
                    template: iportal+'/portal?link=portal/resource/resource-add',
                    controller: namespace+'.add.controller',
                    scope:$scope
                  });
              };

**Comment by why520crazy** [comment]
同样的form在Dialog中就不可以，不在Dialog里面就可以吗？能否提供一个示例 http://plnkr.co/

**Comment by HuDonie** [comment]
不是弹出框的问题，是这里它拿不到viewValueName 
w5cValidator.js

		var $viewValueName = this.formName + "." + elem.name + ".$viewValue";
		console.log($viewValueName);
		

jsp

		  <div class="form-group">
			<label class="control-label col-md-3"><span style='color:red'>*</span>&nbsp;是否可用：</label>
			<div class="col-md-9">
				<label class="radio-inline">
					<input type="radio" ng-model="obj.isAvailable"  value="Y"  ng-     checked="true"> 可用
				</label>
				<label class="radio-inline">
					<input type="radio" ng-model="obj.isAvailable"  value="N"> 不可用
				</label>
			</div>
		</div>
		

浏览器打印出来

		w5cValidator.js:248 validateForm.title.$viewValue
		w5cValidator.js:248 validateForm.summary.$viewValue
		w5cValidator.js:248 validateForm.link.$viewValue
		w5cValidator.js:248 validateForm.releaseVersion.$viewValue
		w5cValidator.js:248 validateForm.cont.$viewValue
		w5cValidator.js:248 validateForm.orderby.$viewValue
		w5cValidator.js:248 validateForm.15.$viewValue
		angular.js:12520 Error: [$parse:syntax] Syntax Error: Token '.15.' is an unexpected token at column 13 of the expression [validateForm.15.$viewValue] starting at [.15.$viewValue].
		http://errors.angularjs.org/1.4.8/$parse/syntax?p0=.15.&p1=is%20an%20unexpected%20token&p2=13&p3=validateForm.15.%24viewValue&p4=.15.%24viewValue
			at http://localhost:8080/iportal/static/lib/plugins/angular-1.4.8/angular.js:68:12
			at Object.AST.throwError (http://localhost:8080/iportal/static/lib/plugins/angular-1.4.8/angular.js:13100:11)
			at Object.AST.ast (http://localhost:8080/iportal/static/lib/plugins/angular-1.4.8/angular.js:12870:12)
			at Object.ASTCompiler.compile (http://localhost:8080/iportal/static/lib/plugins/angular-1.4.8/angular.js:13319:31)
			at Parser.parse (http://localhost:8080/iportal/static/lib/plugins/angular-1.4.8/angular.js:14189:29)
			at $parse (http://localhost:8080/iportal/static/lib/plugins/angular-1.4.8/angular.js:14291:39)
			at Scope.$watch (http://localhost:8080/iportal/static/lib/plugins/angular-1.4.8/angular.js:15482:19)
			at initElement (http://localhost:8080/iportal/static/lib/plugins/angular-w5c-validator/w5cValidator.js:251:36)
			at link (http://localhost:8080/iportal/static/lib/plugins/angular-w5c-validator/w5cValidator.js:298:30)
			at invokeLinkFn (http://localhost:8080/iportal/static/lib/plugins/angular-1.4.8/angular.js:8841:9) <form w5c-form-validate="validateOptions" novalidate="" name="validateForm" class="form-horizontal  w5c-form ng-pristine ng-valid">

**Comment by why520crazy** [comment]
validateForm.15.$viewValue 这个15是从哪里来的

**Comment by HuDonie** [comment]
我知道原因了，这里没有给name属性，我不需要验证的都要给name属性
              
       <input type="radio" ng-model="obj.isAvailable"  value="N"> 不可用

**Comment by why520crazy** [comment]
是这样的，如果没有给name属性的话，浏览器好像给 radio 一个默认的name 是数字，所以js中以数字为命名的话会报错，我可以修改下代码兼容数字的name，如果name是数字不做任何处理

**Comment by why520crazy** [comment]
你目前的解决方案就是给个name就好了

**Comment by HuDonie** [comment]
是的，谢谢why520crazy支持 ，有空出来吃个饭

**Comment by why520crazy** [comment]
好的，哈哈

**Comment by why520crazy** [comment]
2.4.10  版本兼容了name以数字开头的BUG，如果是数字开头不做验证处理
