### ISSUE TITLE
请问，如何动态给form设置name值？

### ISSUE THREAD

**Issue by is8** [why520crazy/angular-w5c-validator#47]
我同一个页面有多个动态生成的form，希望可以把form的name设置成变量，避免冲突。但是我尝试绑定了一下，或者在指令中去改写form，都不能影响到验证组件所获取到的name值，请问这个有没有办法解决呢？

**Comment by why520crazy** [comment]
尝试使用动态 name 指令   w5c-dynamic-element 和 w5c-dynamic-name
