### ISSUE TITLE
修正个bug

### ISSUE THREAD

**Issue by realskyzou** [why520crazy/angular-w5c-validator#50]
在某些不是基于textarea开发的文本编辑器中，按回车会自动提交。
修改了下
 ` if (ctrl.needBindKeydown) {
                        form.bind("keydown keypress", function (event) {
                            if (event.which === 13) {
                                var currentInput = document.activeElement;
                                if (currentInput.type&&currentInput.type !== "textarea") {`

增加currentInput.type&&判断，就不会自动提交表单了。

**Comment by why520crazy** [comment]
好的

**Comment by why520crazy** [comment]
你能直接 提交 pull request 吗？

**Comment by realskyzou** [comment]
已pull

**Comment by why520crazy** [comment]
升级到 v2.4.12 即可
