### ISSUE TITLE
可不可以给不同表单单独设置不同的提示信息

### ISSUE THREAD

**Issue by liaohui1080** [why520crazy/angular-w5c-validator#52]
w5cValidatorProvider.setRules({
        email         : {
            required: "输入的邮箱地址不能为空",
            email   : "输入邮箱地址格式不正确"
        },
        username      : {
            required      : "输入的用户名不能为空",
            pattern       : "用户名必须输入字母、数字、下划线,以字母开头",
            w5cuniquecheck: "输入用户名已经存在，请重新输入"
        },
        password      : {
            required : "密码不能为空",
            minlength: "密码长度不能小于{minlength}",
            maxlength: "密码长度不能大于{maxlength}"
        },
        repeatPassword: {
            required: "重复密码不能为空",
            repeat  : "两次密码输入不一致"
        },
        number        : {
            required: "数字不能为空"
        },
        customizer    : {
            customizer: "自定义验证数字必须大于上面的数字"
        }
    });
这是全局的, 
我想让单独的表单显示不同的提示信息, 这个怎么弄,

**Comment by why520crazy** [comment]
这个 json，key是表单内元素的名称，如果不同表单的元素名称都是 username，那提示信息不一样的可能性不大，即使有，简单处理就是2个表单的元素name设置成不一样，如：
`{
 username1 : {
   required : "输入的用户名不能为空1",
   pattern : "用户名必须输入字母、数字、下划线,以字母开头1"
 },
 username2 : {
   required : "输入的用户名不能为空2",
   pattern : "用户名必须输入字母、数字、下划线,以字母开头2"
}
}`

如果非要自己单独设置也是可以的，你在每个表单的controller里面注入w5cValidator使用 w5cValidator .setRules({});

**Comment by liaohui1080** [comment]
恩,谢谢,写的很详细, 非常感谢
