### ISSUE TITLE
对 select 或者 ui-select 不能焦点移除时候进行验证

### ISSUE THREAD

**Issue by liaohui1080** [why520crazy/angular-w5c-validator#53]
不知道这样一个问题 发个新贴的方式 是否符合你的要求

对 select 或者 ui-select 不能焦点移除时候进行验证

**Comment by why520crazy** [comment]
对于普通的select输入框是可以的，你可以看示例 http://localhost:63342/w5c-validator-ng/example/index.html ，对于  ui-select  已经不是普通的select元素了，所以默认是不支持的

**Comment by why520crazy** [comment]
针对 ui-select 你可以默认给个初始的值，这样就不需要验证 ui-select 了

**Comment by liaohui1080** [comment]
收到了 ,谢谢

**Comment by why520crazy** [comment]
ui-select 可以写个隐藏的 select 进行验证，然后 ui-select 根据这个 select 是否验证成功显示错误样式即可
