### ISSUE TITLE
请问服务端返回错误信息，比如密码错误，怎么展示呢，有接口吗？

### ISSUE THREAD

**Issue by yuanoook** [why520crazy/angular-w5c-validator#55]

**Comment by why520crazy** [comment]
向 form.$errors 里面push一条记录，然后界面展示 form.$errors，对于form的验证，所有的错误提示也是在 form.$errors 的

**Comment by yuanoook** [comment]
可是想直接提示到具体的输入框，密码错误就提示到密码输入框，有办法吗

**Comment by why520crazy** [comment]
这个得 你自己操作DOM实现，目前是不支持的

**Comment by why520crazy** [comment]
2.5.2 已经支持 https://github.com/why520crazy/angular-w5c-validator/blob/master/CHANGELOG.md
