### ISSUE TITLE
错误 $$animateJs is not a function

### ISSUE THREAD

**Issue by 16code** [why520crazy/angular-w5c-validator#58]
`TypeError: $$animateJs is not a function`
angular.module("w5c.validator", ["ng"])  请问这里的依赖 ng 是什么？我在不使用ng模块的时候，程序不报错，但是验证表单不会工作， 如果我加上依赖模块会抛出  $$animateJs is not a function 的错误

**Comment by why520crazy** [comment]
ng 是 angular自带的模块，不加也没有问题，示例中不加是可以显示的，加上并没有报  $$animateJs is not a function 的错误，不知道你具体是怎么使用的

**Comment by 16code** [comment]
谢谢，问题已得到解决，我在使用 w5c Provider的时候忘记依赖注入导致默认配置没生效，但是在ng-strict-di模式下也并未报错

**Comment by why520crazy** [comment]
好的
