### ISSUE TITLE
1.3-1.4版本的angularjs w5c-dynamic-element 指令异常

### ISSUE THREAD

**Issue by jfzhao** [why520crazy/angular-w5c-validator#60]
该指令好像只能运行在1.2环境下。

**Comment by jfzhao** [comment]
兄弟，我发现不加name就正常了。
但是错误信息的匹配有问题，然后我扩展了以$符结尾做近似处理的代码解决了。

**Comment by why520crazy** [comment]
你升级到最新版本吧，以前的中间版本或许有问题，如果最新版没有问题 建议你升级

**Comment by why520crazy** [comment]
你使用的Angular js 是 1.3-1.4? w5cValidator 版本是多少

**Comment by jfzhao** [comment]
v2.4.14

**Comment by jfzhao** [comment]
另外我貌似错误的提交了代码到你的主库里了，你可以看看。

**Comment by jfzhao** [comment]
https://github.com/why520crazy/angular-w5c-validator/compare/master...jfzhao:master

**Comment by why520crazy** [comment]
http://blog.ngnice.com/angular-w5c-validator/example/index.html  示例使用的是 1.4.8， 没有你说的问题，不知道你是怎么使用的？

**Comment by jfzhao** [comment]
我的说法有点问题，如下的使用场景下，在低版本的angularjs中可以正常使用，而在高版本的angularjs中需要去除**name=“repeat”**,并且错误信息无法正确的匹配。

`<div class="form-group" ng-repeat="r in repeatTest">`

                `<div class="col-sm-10">
                    <input type="text" required="" ng-model="r" name="repeat" w5c-dynamic-name="'repeat'+$index" w5c-dynamic-element class="form-control"
                           placeholder="">
                </div>`
`</div>`

**Comment by why520crazy** [comment]
你升级到 2.4.15，name 命名的时候使用 `name$数字$` ，匹配验证规则的时候会忽略 `$数字$`
