### ISSUE TITLE
特定的页面可以设定特定的规则吗?

### ISSUE THREAD

**Issue by lomotony** [why520crazy/angular-w5c-validator#61]
看了下文档也试了一下，发现不能在特定的页面去设置特定的错误显示，还是必须得在全局去设置，这个太不人性化了。同样的名字，会有不一样的错误提示，比如说“请输入商品名”，“请输入用户名”， “请输入标签名“，难道每一个我都要用一个不一样的name?全局去设置?

**Comment by why520crazy** [comment]
你可以在controller里面设置，还有就是name一样，错误信息基本都差不多， username 提示不会说：‘请输入标签名’ 吧

**Comment by lomotony** [comment]
用的时候出了点问题，现在解决了，谢谢！ @why520crazy

**Comment by why520crazy** [comment]
不客气
