### ISSUE TITLE
能支持i18n多语言验证嘛？

### ISSUE THREAD

**Issue by samkk** [why520crazy/angular-w5c-validator#64]
RT 谢谢

**Comment by why520crazy** [comment]
多语言需要你自己通过 服务去设置初始化的错误信息

**Comment by samkk** [comment]
@why520crazy 谢谢作者回复，插件非常好用

**Comment by why520crazy** [comment]
因为比较小的插件，语言包就默认的一些提示信息，为了这个加很多种语言也不值得，所以留了一个入口让用户根据自己的语言定义默认提示信息
