### ISSUE TITLE
MD写的不太对

### ISSUE THREAD

**Issue by milobluebell** [why520crazy/angular-w5c-validator#65]
说实话..我按照你写的这个useage去做，启动都没启动。

**Comment by milobluebell** [comment]
有没有人能告诉我一下这个怎么启动啊。。难道不是引入依赖，写Config，然后指定INPUT的required等等的验证规则？？？

**Comment by milobluebell** [comment]
兄弟啊，按照你http://blog.ngnice.com/angular-w5c-validator/example/index.html 这里的使用说明 或  Readme文档去做，真的能启动吗？  form上的w5c-form-validate属性又是什么呢？

**Comment by why520crazy** [comment]
什么情况
