### ISSUE TITLE
字符范围问题

### ISSUE THREAD

**Issue by anna647** [why520crazy/angular-w5c-validator#66]
这个输入框值长度的验证，只能分两部分吗？最大值和最小值？如果我想提示用户输入值的长度在minlength-maxlength这个范围内，在minlength属性内，maxlength值识别不了，反之亦然。这怎么处理？还有如果后台有返回错误提示，我看了你说是要form.$error.push，具体怎么用能不能给个例子啊，这个form是表单名字吗？灰常谢谢

**Comment by anna647** [comment]
绑定的ng-focus事件好像也没有调用，这又该怎么解决啊？

**Comment by why520crazy** [comment]
我不知道你具体的需求的是什么，如果你同时设置了  minlength 和 maxlength，那就要确保 minlength 设置的值必须小于 maxlength，当输入小于 minlength 的值时这个元素验证不通过，minlength 和 maxlength 都验证不通过，一般针对这种错误处理统一显示一种错误，没有必要分开

关于说的 form.$errors.push 这个 form 就是表单的名字，$errors 主要是处理所有的错误统一显示的，如果每个表单元素显示的错误提示就在表单后面是不需要这个属性，服务端返回错误需要另外处理，你放form.$errors里面也可以，放其他地方也可以，直接 alert 也是可以的，看你产品的需求。
