### ISSUE TITLE
required 对于动态的disabled没有作用

### ISSUE THREAD

**Issue by penghaozhong** [why520crazy/angular-w5c-validator#68]
<input type="url" disabled="" ng-model="vm.entity.disabled" name="disabled" class="form-control" placeholder="该属性已经禁用">
这样写没有问题，但页面中这个元素不是禁用的，是通过选项卡来控制是否禁用时，required 对disabled的愿意也会进行验证，请问大神有好的建议吗？

**Comment by why520crazy** [comment]
1种做法是改产品，切换选项卡就把之前的元素remove掉，通过ng-if + w5c-dynamic-element 控制元素是否验证，这个最快速的处理方式；
第二种是自己写指令调用 w5cFormValidate 指令 controller 的 initElement 和 removeElementValidation 方法来控制是否需要验证这个元素，需要对ng的指令有比较深入的了解，可以参考 w5cDynamicElement 的做法
