### ISSUE TITLE
有不有api用来扩展验证方法

### ISSUE THREAD

**Issue by xingzhezhang** [why520crazy/angular-w5c-validator#70]
例如：想加一个自定义验证方法，但又不想在你的文件中改（以免破坏你的结构，后续更新发布的新版本也方便）

**Comment by why520crazy** [comment]
当然可以，你只要初始化把默认的错误提示添加到对象的 Rules 里面即可

**Comment by why520crazy** [comment]
你可以参考默认的几个自定义的 directive 写法去些
