### ISSUE TITLE
提示消息配置，如果字段名称相同但在不同表单中有不同的意思怎么配置呢

### ISSUE THREAD

**Issue by dcdlove** [why520crazy/angular-w5c-validator#73]
例如在个人资料控制器有一个字段名称是desc 作用是描述，但是在另一个控制器 这个desc 又是别的意思
但是配置 提示是根据表单字段名称来区分的，好尴尬。。。怎么破
---------------------------------------------------------------
就是说在不同控制器下如何 定制不同的 验证提示、、、、谢谢作者，辛苦了

**Comment by dcdlove** [comment]
额。。。忘记了这个验证插件是服务，直接在控制器下重新配置规则就可以了。。。。好尴尬。。。才缓过神

**Comment by why520crazy** [comment]
哈哈哈，可以设置不同的名字或者在每个controller修改规则
