### ISSUE TITLE
使用w5c-repeat时报错

### ISSUE THREAD

**Issue by amingguazi** [why520crazy/angular-w5c-validator#76]
`        <div class="form-group">
            <label class="col-sm-2 control-label">密码:</label>
            <div class="col-sm-3">
                <input type="password" name="Password" class="form-control" ng-model="editUser.userData.password" ng-minlength="8" ng-maxlength="15" required>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">重复密码:</label>
            <div class="col-sm-3">
                <input type="password" name="RepeatPassword" class="form-control" w5c-repeat="Password" ng-model="editUser.userData.repeatPassword" required>
            </div>
        </div>`

会提示 Cannot read property 'Password' of undefined

**Comment by why520crazy** [comment]
仔细看示例 http://blog.ngnice.com/angular-w5c-validator/example/index.html ，这里面有 ng-repeat 

你贴的代码不全，无法知道原因，看 form 的 name 有没有指定，或者 控制台有没有报其他的错误
