### ISSUE TITLE
用该插件，键盘回车的时候没有触发表单提交。如何设置？

### ISSUE THREAD

**Issue by HuangMingChao** [why520crazy/angular-w5c-validator#81]
用该插件，键盘回车的时候没有触发表单提交，导致登录这类的功能。填写完直接回车没有反应。

**Comment by why520crazy** [comment]
一般默认回车是会自动提交的，请你断点调试下，是不是js报错了

**Comment by why520crazy** [comment]
示例回车就是自动提交的， 必须有 w5c-form-submit 指令才可以正常提交，你确认下使用是否正确
