### ISSUE TITLE
能否主动的去触发表单里面的某一项的验证

### ISSUE THREAD

**Issue by HuangMingChao** [why520crazy/angular-w5c-validator#82]
能否主动的去触发表单里面的某一项的验证，例如我有两个输入框和一个按钮。有没有方法让我自定义该按钮触发哪一个输入框的验证。而不是全部验证。

**Comment by why520crazy** [comment]
目前不可以

**Comment by why520crazy** [comment]
你可以通过2个表单来解决你的需求

**Comment by why520crazy** [comment]
升级到 5.2.1 现在支持只验证单个表单元素 https://github.com/why520crazy/angular-w5c-validator/blob/master/CHANGELOG.md
