### ISSUE TITLE
ng-peprat中的w5c-dynamic-name

### ISSUE THREAD

**Issue by lwIcons** [why520crazy/angular-w5c-validator#83]
动态添加表格中需要检验的元素,w5c-dynamic-name属性值中含有$index,
打乱顺序添加时,w5c-dynamic-name属性值会更新,但是w5c-dynamic-name指令创建的name属性值没有更新,导致出现多个校验元素name属性值相同,校验失效

**Comment by why520crazy** [comment]
如果顺序有变化就不要使用 $inde 有唯一 id 之类的吗？ 如果要实时变就需要检测这个 name 属性了
