### ISSUE TITLE
重复验证

### ISSUE THREAD

**Issue by kingdee88** [why520crazy/angular-w5c-validator#84]
使用  input  type="number" 进行重复验证的时候   由于 w5c 取得2次值 类型不同，通不过验证。

版本：v2.4.25 
       源码中：  ngModel.$parsers.push(function (value) {

                            if (value ===otherInput.$viewValue) {
                                ngModel.$setValidity("repeat", true);
                            } else {
                                ngModel.$setValidity("repeat", false);
                            }
                            return value;
                        });

otherInput.$viewValue的类型为 string 
value 的类型为 number

**Comment by why520crazy** [comment]
已经修复了  升级到 5.2.4 版本即可
