### ISSUE TITLE
动态表单验证问题；

### ISSUE THREAD

**Issue by Guxingzhe** [why520crazy/angular-w5c-validator#87]
在一个表单中，我们需要针对某一个input动态添加其验证，切换状态了，又不需要对其进行验证。貌似没有移除注册对应表单的的验证的方法

**Comment by Guxingzhe** [comment]
还有一个问题，就是我可能存在多个表单，每个表单用一个controller进行管理，我要怎么样才能在controller里面配置对应的表单配置；对其进行校验等？w5cValidatorProvider应该只是提供一个统一的配置而已，并不能针对作用域进行配置和管理；

**Comment by Guxingzhe** [comment]
在一个表单中，我们需要针对某一个input动态添加其验证，切换状态了，又不需要对其进行验证。貌似没有移除注册对应表单的的验证的方法

**Comment by Guxingzhe** [comment]
本人修改基于v2.5.7修改的一个版本；
http://pan.baidu.com/s/1i4Fiw7r
1、支持实时输入进行校验；
2、支持动态改变单个元素是否加入验证状态；
温馨提示：index-local.html这种写法，支持直接$scope[formName][作者拓展方法]在controller中调用；不过$scope[formName]这个对象只有当指令执行完后才存在；
如下是效果图：
![image](https://user-images.githubusercontent.com/9564255/31324030-c32eba64-ace0-11e7-91fa-6a357d56b2d8.png)
![image](https://user-images.githubusercontent.com/9564255/31324042-d61e3a00-ace0-11e7-9057-29723c381c00.png)

**Comment by why520crazy** [comment]
1. 关于 changTrig 属性控制实时校验如果你感兴趣可以提交 Pull Request
2. 对于单独移除某个验证元素，其实是有内部方法的，W5cFormValidateCtrl 中的removeElementValidation 就是做这个的，只是没有暴露出去

**Comment by Guxingzhe** [comment]
removeElementValidation 作为内部方法，我也没有暴露出来。而是通过某个变量，监听其true或者false来判断是否给对应的input添加校验；因此拓展了指令w5c-dynamic-element，在里面对值进行watch，判断是true或者false再对对应的input添加或者移除校验；
本人代码写的有点挫不该乱提交代码。本人代码仅供参考！

**Comment by why520crazy** [comment]
动态表单验证 ng1 做的比较差，ng2+ 修复了这些坑，https://github.com/why520crazy/ngx-validator 这个是 Angular  2+的一个验证类库
