### ISSUE TITLE
使用w5cuniquecheck报$http.get.success错误

### ISSUE THREAD

**Issue by superkerio** [why520crazy/angular-w5c-validator#92]
angularjs后面的版本$http没有success，error方法，只有then方法

**Comment by why520crazy** [comment]
嗯，这个会修复，目前你可以自定义一个复写原有的指令

**Comment by why520crazy** [comment]
暂时不修复了，推荐升级到 Angular 2+，使用 https://github.com/why520crazy/ngx-validator
