### ISSUE TITLE
w5cDynamicName 名称无法正确更新

### ISSUE THREAD

**Issue by jfzhao** [why520crazy/angular-w5c-validator#94]
![image](https://user-images.githubusercontent.com/8497438/48108511-55521700-e27e-11e8-9c28-850422071821.png)
我使用index组合生成录入组件的name,在我向循环的数组头部插入一个元素,原来的index为0的组件并不会更新成新的name,span后的0,1,2是我通过双向绑定输出的index值.

**Comment by jfzhao** [comment]
我尝试更改了w5cDynamicName指令,虽然可以正确的更新name但是验证信息的show和remove的触发就变得十分混乱.
![image](https://user-images.githubusercontent.com/8497438/48108732-4c157a00-e27f-11e8-8fcb-19b8f9fb7cc7.png)

**Comment by why520crazy** [comment]
如果修改了名字需要把之前的 Control 移除，然后再追加到 FormControl 中去

建议升级到 Angular 2+ ，使用 https://github.com/why520crazy/ngx-validator 类库，Angular 2+ 填了 Angular.js 的很多坑

**Comment by jfzhao** [comment]
升到2+ 需要面对的坑就更多了 ORZ~ 这个项目是不行了 下个吧~

**Comment by jfzhao** [comment]
感谢2+的验证插件的分享先，解决了我一个组件的问题。还有12345678....

**Comment by why520crazy** [comment]
好的，加油，升级是必然的趋势，就是看时间和资源了
